config/routes.rb
Zapwire::Application.routes.draw do

  root :to => "specials#index"

  resources :users

  resources :vendors do
      resources :specials
  end

  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :specials, :only => [:index]

end

app/models/special.rb
class Special
  include Mongoid::Document
  field :shortdesc, :type => String
  field :desc, :type => String
  field :price, :type => Float
  field :avail, :type => Date

  embedded_in :vendor
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  skip_before_filter :require_login, :only => [:index]
  respond_to :html

  # GET /specials
  # GET /specials.json
  def index
    # index should take a param 
    if params[:lat].present? && params[:lon].present?
      # need all the vendors near first
      #@vendors = Vendor.near([params[:lat], params[:lon]], 20)
      #logger.debug params[:lat]
      #logger.debug params[:lon]
      tmpv = Vendor.new
      #tmpv.coordinates = [params[:lat], params[:lon]]
      tmpv.coordinates = [params[:lon], params[:lat]]
      #@cords = tmpv.coordinates.inspect
      @vendors = tmpv.nearbys(1000000).to_a
      @specials = []
      @vendors.each do |vendor|
        vendor.specials.each do |special|
          @specials << special
        end
      end 

      respond_to do |format|
        format.html { render :partial => "index", :layout => false }
        format.json { render json: @specials }
      end
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @specials }
      end
    end
  end

  # GET /specials/1
  # GET /specials/1.json
  def show
    @special = Special.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @special }
    end
  end

  # GET /specials/new
  # GET /specials/new.json
  def new
    @vendor = Vendor.find(params[:vendor_id])
#      @special = Special.new
    @special = @vendor.specials.build

    respond_with(@special)

#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @special }
#    end
  end

  # GET /specials/1/edit
  def edit
    @special = Special.find(params[:id])
  end

  # POST /specials
  # POST /specials.json
  def create

    @vendor = Vendor.find(params[:vendor_id])
    #@special = Special.new(params[:special])
    @special = @vendor.specials.build(params[:special])

    #respond_with(@special)

    respond_to do |format|
      if @special.save
        #format.html { redirect_to @special, notice: 'Special was successfully created.' }
        format.html { redirect_to vendor_specials_path(@vendor), notice: 'Special was successfully created.' }
        format.json { render json: @special, status: :created, location: @special }
      else
        format.html { render action: "new" }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specials/1
  # PUT /specials/1.json
  def update
    @special = Special.find(params[:id])

    respond_to do |format|
      if @special.update_attributes(params[:special])
        format.html { redirect_to @special, notice: 'Special was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specials/1
  # DELETE /specials/1.json
  def destroy
    @special = Special.find(params[:id])
    @special.destroy

    respond_to do |format|
      format.html { redirect_to specials_url }
      format.json { head :ok }
    end
  end
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/specials/_form.html.erb
<%= form_for(@special) do |f| %>
  <% if @special.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@special.errors.count, "error") %> prohibited this special from being saved:</h2>

      <ul>
      <% @special.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shortdesc %><br />
    <%= f.text_field :shortdesc %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :avail %><br />
    <%= f.text_field :avail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specials/_index.html.erb
<% @specials.each do |special| %>
  <li class='special'>
  <a href='#special_info'>
    <h2 class='special_title'><%= special.shortdesc %></h2>
    <p class='vendor_info'>
    <span class='vendor_name'><%= special.vendor.name %></span> -
    <span class='vendor_dist'>1.4</span>mi
    </p>
    <p class='special_price'>4<sup>99</sup></p>
  </a>
  </li>
<% end %>

app/views/specials/edit.html.erb
<h1>Editing special</h1>

<%= render 'form' %>

<%= link_to 'Show', @special %> |
<%= link_to 'Back', specials_path %>

app/views/specials/index.html.erb
<content id='main_list'>
  <div class='status_bar'>
    <p id='special_filter'>
    Specials happening 
    <a id='filter_time' href='#'>now</a> by 
    <a id='filter_sort' href='#'>distance</a> near 
    <a id='filter_loc'  href='#'>you</a>
    </p>
  </div>
  <ul class='special_list'>
  </ul>
</content>
<content id='special_info'>
  <div class='status_bar'>
    <a href='#main_list'>&lt;&lt;</a>       
  </div>
  <div id='selected_special'>
    <div class='special'>
      <a href='#special_info'>
        <h2 class='special_title'>Souper Salad Combo</h2>
        <p class='vendor_info'>
        <span class='vendor_name'>Dave's Salad</span> -
        <span class='vendor_dist'>1.4</span>mi
        </p>
        <p class='special_price'>4<sup>99</sup></p>
      </a>
    </div>
    <p class='special_desc'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dictum enim ac nisl. Donec adipiscing, nulla in accumsan fringilla, purus augue porttitor justo, non congue quam metus et sem.</p>
  </div>
  <div id='vendor_specials'>
    <h3>Other specials from Bob's Burgers:</h3>
    <ul class='special_list'>
      <li class='special'>
      <a href='#special_info'>
        <h2 class='special_title'>Healthy Fruit Salad</h2>
        <p class='vendor_info'>
        <span class='vendor_name'>MaMa YumYum</span> -
        <span class='vendor_dist'>1.7</span>mi
        </p>
        <p class='special_price'>2<sup>89</sup></p>
      </a>
      </li>
    </ul>
  </div>
</content>
<script src='js/geoloc.js'></script>

app/views/specials/new.html.erb
<h1>New special</h1>

<%= form_for(@special, :url=>vendor_specials_path(@vendor)) do |f| %>
  <% if @special.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@special.errors.count, "error") %> prohibited this special from being saved:</h2>

      <ul>
      <% @special.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shortdesc %><br />
    <%= f.text_field :shortdesc %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :avail %><br />
    <%= f.text_field :avail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', vendor_specials_path %>

app/views/specials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Shortdesc:</b>
  <%= @special.shortdesc %>
</p>

<p>
  <b>Desc:</b>
  <%= @special.desc %>
</p>

<p>
  <b>Price:</b>
  <%= @special.price %>
</p>

<p>
  <b>Avail:</b>
  <%= @special.avail %>
</p>


<%= link_to 'Edit', edit_special_path(@special) %> |
<%= link_to 'Back', specials_path %>