config/routes.rb
Zapwire::Application.routes.draw do

  root :to => "specials#index"

  resources :users

  resources :vendors do
      resources :specials
  end

  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :specials, :only => [:index]

end

app/models/vendor.rb
class Vendor
  include Mongoid::Document
  include Geocoder::Model::Mongoid
  field :gid, :type => String
  field :name, :type => String
  field :coordinates, :type => Array
  field :address, :type => String
  field :phone, :type => String

  validates_presence_of :name
  validates_presence_of :address
  validates_presence_of :phone

  geocoded_by :address               # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  reverse_geocoded_by :coordinates
  after_validation :reverse_geocode  # auto-fetch address

  embeds_many :specials

  belongs_to :user

  accepts_nested_attributes_for :specials, :autosave => true
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  #skip_before_filter :require_login, :only => [:index]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = current_user.vendors.all.to_a

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vendors }
    end
  end

#  def search
#    @vendors = Vendor.
#    respond_to do |format|
#      format.html # index.html.erb
#      format.json { render json: @vendors }
#    end
#  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new
    @vendor.specials.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])
    current_user.vendors << @vendor

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render json: @vendor, status: :created, location: @vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1>Listing vendors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vendors.each do |vendor| %>
  <tr>
    <td><%= vendor.name %></td>
    <td><%= vendor.address %></td>
    <td><%= link_to 'Show', vendor %></td>
    <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
    <td><%= link_to 'Destroy', vendor, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'Add Special', new_vendor_special_path(vendor) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gid:</b>
  <%= @vendor.gid %>
</p>

<p>
  <b>Name:</b>
  <%= @vendor.name %>
</p>


<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>